language: cpp

notifications:
  irc:
    channels:
      - "irc.quakenet.org#jk2mv"
    template:
      - "%{repository} (%{commit}): %{commit_subject}"
      - "%{message} Details: %{build_url}"

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      env: HOST=linux-x86_64-package
    - os: linux
      dist: trusty
      sudo: required
      env: HOST=linux-x86_64-portable
    - os: osx
      osx_image: xcode8.3
      env: HOST=macosx-x86_64-app
    - os: osx
      osx_image: xcode8.3
      env: HOST=macosx-x86_64-portable

before_install: |
  git fetch --unshallow

  if [[ "$HOST" == linux-x86_64-* ]]; then
      docker pull ubuntu:16.04
      docker run --name bc -v $TRAVIS_BUILD_DIR:/jk2mv --cap-add SYS_ADMIN --device /dev/fuse -td ubuntu:16.04 /bin/bash
  fi
  
  if [[ "$HOST" == macosx-* ]]; then
      export MACOSX_DEPLOYMENT_TARGET=10.9
  fi

install: |
  if [[ "$HOST" == linux-* ]]; then
      docker exec bc apt update
      docker exec bc apt -y install git cmake zip wget libfuse2 build-essential libsdl2-dev libgl1-mesa-dev libopenal-dev libjpeg-dev libpng-dev libminizip-dev
  else
      cd ~
      curl -O https://www.libsdl.org/release/SDL2-2.0.8.tar.gz
      tar xzf SDL2-2.0.8.tar.gz
      cd SDL2-2.0.8/Xcode/SDL
      sed -i -e 's/@rpath//g' SDL.xcodeproj/project.pbxproj
      xcodebuild -configuration Release
      mkdir -p ~/Library/Frameworks/
      ln -s `pwd`/build/Release/SDL2.framework ~/Library/Frameworks/
  fi

script: |
  mkdir $TRAVIS_BUILD_DIR/build/travis
  cd $TRAVIS_BUILD_DIR/build/travis

  if [[ "$HOST" == linux-* ]]; then
      if [[ "$HOST" == *-portable ]]; then
          docker exec bc sh -c "cd /jk2mv/build/travis && cmake -DUseInternalLibs=ON -DBuildPortableVersion=ON ../.."
          docker exec bc sh -c "cd /jk2mv/build/travis && make"
          docker exec bc sh -c "cd /jk2mv/build/travis && make package"
      else
          docker exec bc sh -c "cd /jk2mv/build && ./build-appimage.sh"
          docker exec bc sh -c "cd /jk2mv/build && mv ./*-appimage/out ./travis"
      fi
  else
      if [[ "$HOST" == *-portable ]]; then
          cmake -G "Unix Makefiles" -DUseInternalLibs=ON -DBuildPortableVersion=ON ../..
      else
          cmake -G "Unix Makefiles" -DUseInternalLibs=ON -DBuildPortableVersion=OFF ../..
      fi

      make
      make package
  fi

after_script: |
  if [[ "$HOST" == linux-* ]]; then docker stop bc; fi

before_deploy: |
  cd $TRAVIS_BUILD_DIR
  sed -i -e "s/@MV_VERSION@/$(git describe --tags)/g" tools/bintray.json
  sed -i -e "s/@MV_DATE@/$(date -u +"%Y-%m-%d")/g" tools/bintray.json

deploy:
  - provider: bintray
    file: "tools/bintray.json"
    user: "ouned"
    key:
      secure: "PwC5cJhxU08pJSFU6ao8Z1EitXNvud5J45m65u+b+/BDnxB2xq95XGmhPBgr7RZDerQDDVStKH8Dw9HPjPmRChRi/DAxjitY49ggExI6o3wCzxum8aG7MDGv+BALFJW3QPxnf5pgY7zi0RsVbionRhEOyHbI4ANs8hyEzgfJ5aU="
    skip_cleanup: true
    on:
      tags: false

  - provider: releases
    file_glob: true
    file: "build/travis/out/*.{AppImage,dmg,tar.gz}"
    api_key:
      secure: "Uo5ezYFbjZRfGZYm3i5dyqZooBr2JcFSp3XQWpFQBbHWXFPZ2DDcgr4LcahuvKhO8660XDh8TS8GdmfslgYEwEARYFSt68lU5cHx85dpuuVRxkhZKFpgZMY6YOMxkzpkJwtZtFWGla784oe5v3X1nlzYp11oxhKkuhwZe0iJsC0="
    skip_cleanup: true
    on:
      tags: true
