language: cpp
sudo: required
dist: trusty

env:
  global:
    - "FTP_SERVER=ftp://jk2mv.org"
    - "FTP_USER=ounedcideploy"
    - secure: "XZBwOWePycNX1Ce4/e8ZKveZYwoWjZYYdYLCN5yk3hDTRvMKTI1n2xBWbsyNjZ35Ep3MYyq9KKA7YqQ9whvV7k3IcK66jUfViWaqvKuu3gm7+pdpyEWHbx5m8uQGqL4irlB2Zo1eNw9QMPwRpaM2hQDCDV8AIzBR4axPIralCOE="

notifications:
  irc:
    channels:
      - "irc.quakenet.org#jk2mv"
    template:
      - "%{repository} (%{commit}): %{commit_subject}"
      - "(%{result}): %{message}"
      - "Build details: %{build_url}"

matrix:
  include:
    - os: linux
      env: HOST=linux-x86_64-gcc
    - os: osx
      env: HOST=macosx-universal-clang

before_install:
  - git fetch --unshallow
  - if [[ "$HOST" == linux-x86_64-gcc ]]; then sudo apt-get update; fi

install: |
  export MVDIR=`pwd`
  if [[ "$HOST" == linux-x86_64-gcc ]]; then
      sudo aptitude install -y cmake curl rpm debhelper devscripts libsdl2-dev libgl1-mesa-dev libopenal-dev
  else
      cd ~
      curl -O https://www.libsdl.org/release/SDL2-2.0.4.tar.gz
      tar xzf SDL2-2.0.4.tar.gz
      cd SDL2-2.0.4/Xcode/SDL
      sed -i -e 's/@rpath//g' SDL.xcodeproj/project.pbxproj
      xcodebuild -configuration Release
      mkdir -p ~/Library/Frameworks/
      ln -s `pwd`/build/Release/SDL2.framework ~/Library/Frameworks/
  fi

script:
  - cd "$MVDIR/build"
  - mkdir travis_build
  - cd travis_build

  - if [[ "$HOST" == linux-x86_64-gcc ]]; then cmake -G "Unix Makefiles" -DUseInternalPNG=ON -DUseInternalJPEG=ON -DUseInternalZLIB=ON -DUseInternalCURL=ON -DBuildPortableVersion=OFF -DBuildPackDEB=ON -DBuildPackRPM=ON ../..; fi
  - if [[ "$HOST" == macosx-universal-clang ]]; then cmake -G "Unix Makefiles" -DUseInternalPNG=ON -DUseInternalJPEG=ON -DUseInternalZLIB=ON -DUseInternalCURL=ON -DBuildPortableVersion=OFF ../..; fi

  - make
  - make package

after_success: |
  if [[ "${TRAVIS_PULL_REQUEST}" = "false" ]]; then
      cd "$MVDIR/build/travis_build/out"

      for i in *.{deb,rpm,dmg}; do
          curl -T ${i} -u $FTP_USER:$FTP_PASSWORD $FTP_SERVER
      done
  fi
