name: Build

on:
  workflow_dispatch:
  push:
    branches: actions
  pull_request:
    branches: actions

jobs:
  vs2019:
    name: Build VS 2019, ${{ matrix.build_type }}, ${{ matrix.arch }}
    runs-on: windows-2019
    strategy:
      matrix:
        build_type: [Debug, RelWithDebInfo]
        arch: [Win32, x64]

    steps:
    - uses: actions/checkout@v2

    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Create Build Environment
      run: cmake -E make_directory ${{runner.workspace}}/build/actions

    - name: Configure CMake
      shell: bash
      working-directory: ${{runner.workspace}}/build/actions
      run: cmake $GITHUB_WORKSPACE -A ${{ matrix.arch }}

    - name: Build
      working-directory: ${{runner.workspace}}/build/actions
      shell: bash
      run: cmake --build . --config ${{ matrix.build_type }}

  vs2017_xp:
    name: Build VS 2017, Windows XP
    runs-on: windows-2016

    steps:
    - uses: actions/checkout@v2

    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Create Build Environment
      run: cmake -E make_directory ${{runner.workspace}}/build/actions

    - name: Configure CMake
      shell: bash
      working-directory: ${{runner.workspace}}/build/actions
      run: cmake $GITHUB_WORKSPACE -A Win32 -T v141_xp

    - name: Build
      working-directory: ${{runner.workspace}}/build/actions
      shell: bash
      run: cmake --build . --config RelWithDebInfo

  macos:
    name: Build macOS AppleClang
    runs-on: macos-10.15
    strategy:
      matrix:
        portable: [ON, OFF]

    steps:
    - uses: actions/checkout@v2

    - name: Create Build Environment
      run: |
        brew install sdl2
        mkdir -p ${{runner.workspace}}/build/actions

    - name: Configure CMake
      shell: bash
      working-directory: ${{runner.workspace}}/build/actions
      run: cmake -G "Unix Makefiles" -DUseInternalLibs=ON -DBuildPortableVersion=${{ matrix.portable }} ../..

    - name: Build
      working-directory: ${{runner.workspace}}/build/actions
      shell: bash
      run: make

    - name: Package
      working-directory: ${{runner.workspace}}/build/actions
      shell: bash
      run: make package

  linux:
    name: Build Linux, ${{ matrix.build_type }}
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        options: [-DUseInternalLibs=ON -DBuildPortableVersion=ON, -DUseInternalLibs=OFF -DBuildPortableVersion=OFF]

    steps:
    - uses: actions/checkout@v2

    - name: Create Build Environment
      run: |
        sudo apt-get update
        sudo apt-get install git zip wget libfuse2 build-essential libsdl2-dev libgl1-mesa-dev libopenal-dev libjpeg-dev libpng-dev libminizip-dev
        mkdir -p ${{runner.workspace}}/build/actions

    - name: Configure CMake
      shell: bash
      working-directory: ${{runner.workspace}}/build/actions
      run: cmake ${{ matrix.options }} ../..

    - name: Build
      working-directory: ${{runner.workspace}}/build/actions
      shell: bash
      run: build

    - name: Package
      working-directory: ${{runner.workspace}}/build/actions
      shell: bash
      run: build
